### ISSUE TITLE
Setup env vars

### ISSUE THREAD

**Issue by shpsyte** [Cliffback/netcoredbg-macOS-arm64.nvim#1]
Thank you for this source, it seems to be the only one that works in arm64

I struggling to setup the env vars
 
 "env": {
              "ASPNETCORE_ENVIRONMENT": "Development"
          },
          
  Any Idea where can I add it ?

**Comment by Cliffback** [comment]
Happy that it is of use! 

I think you should be able to do it the cs config object towards the bottom of the init.lua in the plugin.

I haven't tested it myself yet. Let me know if it works, and if so, I can perhaps make it possible to set the variable in the setup of this plugin.

```
dap.configurations.cs = {
    {
      type = 'coreclr',
      name = 'NetCoreDbg: Launch',
      request = 'launch',
      cwd = '${fileDirname}',
      program = function()
        return vim.fn.input('Path to dll', get_dll_path(), 'file')
      end,
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
    },
}
```

[Source](https://stackoverflow.com/questions/77216161/how-to-setup-envs-in-neovim-dap-configs-for-dotnet-c)

**Comment by Cliffback** [comment]
I just added both the environment and the url as an input when launching the debugger. Run an update of the plugin and see if that works well for you

What i set:
```
 env = {
        ASPNETCORE_ENVIRONMENT = function()
          return vim.fn.input("ASPNETCORE_ENVIRONMENT: ", "Development")
        end,
        ASPNETCORE_URL = function()
          return vim.fn.input("ASPNETCORE_URL: ", "http://localhost:5000")
        end,
      }
```

**Comment by shpsyte** [comment]
Thank you for the update, it seems to be working with the env property ...
